apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: payment-checkout
  labels:
    app.kubernetes.io/name: traffic-generator
    app.kubernetes.io/part-of: fivepercent-observability-lab
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: traffic-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traffic-generator
        app.kubernetes.io/part-of: fivepercent-observability-lab
    spec:
      containers:
        - name: traffic-generator
          image: fivepercent-observability-traffic-generator:local
          imagePullPolicy: IfNotPresent
          env:
            - name: TARGET_URL
              value: "http://payment-app"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
